[package]
name = "offset-polygon"
version = "0.1.0"
authors = ["Andreas Monitzer <andreas@monitzer.com>"]
edition = "2018"

[dependencies]
geo-types = { version = "0.3", default-features = false }
num-traits = "0.2"
